apiVersion: apps/v1
kind: Deployment
metadata:
  name: libro-read
spec:
  replicas: 3
  selector:
    matchLabels:
      app: libro-read
  template:
    metadata:
      labels:
        app: libro-read
    spec:
      containers:
      - name: libro-read
        image: rflorezeam/libro-update:sha-aa8082a
        ports:
        - containerPort: 8082
        env:
        - name: MONGODB_URI
          value: "mongodb://root:example@libro-mongodb:27017"