apiVersion: v1
kind: Service
metadata:
  name: libro-read-service
spec:
  selector:
    app: libro-read
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort 